# Feature Engineering

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectFromModel
%matplotlib inline
pd.pandas.set_option('display.max_columns',None)

In [2]:
dataset=pd.read_csv('laptops.csv',index_col=0)
dataset.head()

Company      Product   TypeName  Inches                    ScreenResolution  \
1   Apple  MacBook Pro  Ultrabook    13.3  IPS Panel Retina Display 2560x1600   
2   Apple  Macbook Air  Ultrabook    13.3                            1440x900   
3      HP       250 G6   Notebook    15.6                   Full HD 1920x1080   
4   Apple  MacBook Pro  Ultrabook    15.4  IPS Panel Retina Display 2880x1800   
5   Apple  MacBook Pro  Ultrabook    13.3  IPS Panel Retina Display 2560x1600   

                          Cpu   Ram               Memory  \
1        Intel Core i5 2.3GHz   8GB            128GB SSD   
2        Intel Core i5 1.8GHz   8GB  128GB Flash Storage   
3  Intel Core i5 7200U 2.5GHz   8GB            256GB SSD   
4        Intel Core i7 2.7GHz  16GB            512GB SSD   
5        Intel Core i5 3.1GHz   8GB            256GB SSD   

                            Gpu  OpSys  Weight  Price_euros  
1  Intel Iris Plus Graphics 640  macOS  1.37kg      1339.69  
2        Intel HD Graphics 6000  macOS  1.34kg       898.94  
3         Intel HD Graphics 620  No OS  1.86kg       575.00  
4            AMD Radeon Pro 455  macOS  1.83kg      2537.45  
5  Intel Iris Plus Graphics 650  macOS  1.37kg      1803.60

In [3]:
data=dataset.copy()
data['Ram(GB)']=[word.strip('GB') for word in data['Ram']]
data['Ram(GB)']=pd.to_numeric(data['Ram(GB)'])
data['Weight(kg)']=[word.strip('kg') for word in data['Weight']]
data['Weight(kg)']=pd.to_numeric(data['Weight(kg)'])
data.drop(['Weight','Ram'],axis=1,inplace=True)
data.head(50)


Company                                    Product            TypeName  \
1    Apple                                MacBook Pro           Ultrabook   
2    Apple                                Macbook Air           Ultrabook   
3       HP                                     250 G6            Notebook   
4    Apple                                MacBook Pro           Ultrabook   
5    Apple                                MacBook Pro           Ultrabook   
6     Acer                                   Aspire 3            Notebook   
7    Apple                                MacBook Pro           Ultrabook   
8    Apple                                Macbook Air           Ultrabook   
9     Asus                            ZenBook UX430UN           Ultrabook   
10    Acer                                    Swift 3           Ultrabook   
11      HP                                     250 G6            Notebook   
12      HP                                     250 G6            Notebook   
13   Apple                                MacBook Pro           Ultrabook   
14    Dell                              Inspiron 3567            Notebook   
15   Apple                                MacBook 12"           Ultrabook   
16   Apple                                MacBook Pro           Ultrabook   
17    Dell                              Inspiron 3567            Notebook   
18   Apple                                MacBook Pro           Ultrabook   
19  Lenovo                          IdeaPad 320-15IKB            Notebook   
20    Dell                                     XPS 13           Ultrabook   
21    Asus                            Vivobook E200HA             Netbook   
22  Lenovo                         Legion Y520-15IKBN              Gaming   
23      HP                                     255 G6            Notebook   
24    Dell                              Inspiron 5379  2 in 1 Convertible   
25      HP    15-BS101nv (i7-8550U/8GB/256GB/FHD/W10)           Ultrabook   
26    Dell                              Inspiron 3567            Notebook   
27   Apple                                MacBook Air           Ultrabook   
28    Dell                              Inspiron 5570            Notebook   
29    Dell                              Latitude 5590           Ultrabook   
30      HP                                ProBook 470            Notebook   
31   Chuwi                              LapBook 15.6"            Notebook   
32    Asus       E402WA-GA010T (E2-6110/2GB/32GB/W10)            Notebook   
33      HP       17-ak001nv (A6-9220/4GB/500GB/Radeon            Notebook   
34    Dell                                     XPS 13           Ultrabook   
35   Apple                                MacBook Air           Ultrabook   
36  Lenovo                         IdeaPad 120S-14IAP            Notebook   
37    Acer                                   Aspire 3            Notebook   
38    Dell                              Inspiron 5770            Notebook   
39      HP                                     250 G6            Notebook   
40      HP                                ProBook 450            Notebook   
41    Asus  X540UA-DM186 (i3-6006U/4GB/1TB/FHD/Linux)            Notebook   
42    Dell                              Inspiron 7577              Gaming   
43    Asus     X542UQ-GO005 (i5-7200U/8GB/1TB/GeForce            Notebook   
44    Acer                            Aspire A515-51G            Notebook   
45    Dell                              Inspiron 7773  2 in 1 Convertible   
46   Apple                                MacBook Pro           Ultrabook   
47  Lenovo                          IdeaPad 320-15ISK            Notebook   
48    Asus                                  Rog Strix              Gaming   
49    Dell                              Inspiron 3567            Notebook   
50    Asus       X751NV-TY001T (N4200/4GB/1TB/GeForce            Notebook   

    Inches                           ScreenResolution  \
1     13.3        

In [4]:
numerical_features=['Inches','Ram(GB)','Weight(kg)','Price_euros']

In [5]:
#for feature in numerical_features:
 #   data[feature]=np.log(data[feature])
#data.head()

In [6]:
dataset=data.copy()

## Handling Categorical Feature


Combining Company, Product and TypeName features

In [7]:
dataset.head(10)

Company          Product   TypeName  Inches  \
1    Apple      MacBook Pro  Ultrabook    13.3   
2    Apple      Macbook Air  Ultrabook    13.3   
3       HP           250 G6   Notebook    15.6   
4    Apple      MacBook Pro  Ultrabook    15.4   
5    Apple      MacBook Pro  Ultrabook    13.3   
6     Acer         Aspire 3   Notebook    15.6   
7    Apple      MacBook Pro  Ultrabook    15.4   
8    Apple      Macbook Air  Ultrabook    13.3   
9     Asus  ZenBook UX430UN  Ultrabook    14.0   
10    Acer          Swift 3  Ultrabook    14.0   

                      ScreenResolution                         Cpu  \
1   IPS Panel Retina Display 2560x1600        Intel Core i5 2.3GHz   
2                             1440x900        Intel Core i5 1.8GHz   
3                    Full HD 1920x1080  Intel Core i5 7200U 2.5GHz   
4   IPS Panel Retina Display 2880x1800        Intel Core i7 2.7GHz   
5   IPS Panel Retina Display 2560x1600        Intel Core i5 3.1GHz   
6                             1366x768     AMD A9-Series 9420 3GHz   
7   IPS Panel Retina Display 2880x1800        Intel Core i7 2.2GHz   
8                             1440x900        Intel Core i5 1.8GHz   
9                    Full HD 1920x1080  Intel Core i7 8550U 1.8GHz   
10         IPS Panel Full HD 1920x1080  Intel Core i5 8250U 1.6GHz   

                 Memory                           Gpu       OpSys  \
1             128GB SSD  Intel Iris Plus Graphics 640       macOS   
2   128GB Flash Storage        Intel HD Graphics 6000       macOS   
3             256GB SSD         Intel HD Graphics 620       No OS   
4             512GB SSD            AMD Radeon Pro 455       macOS   
5             256GB SSD  Intel Iris Plus Graphics 650       macOS   
6             500GB HDD                 AMD Radeon R5  Windows 10   
7   256GB Flash Storage       Intel Iris Pro Graphics    Mac OS X   
8   256GB Flash Storage        Intel HD Graphics 6000       macOS   
9             512GB SSD          Nvidia GeForce MX150  Windows 10   
10            256GB SSD        Intel UHD Graphics 620  Windows 10   

    Price_euros  Ram(GB)  Weight(kg)  
1       1339.69        8        1.37  
2        898.94        8        1.34  
3        575.00        8        1.86  
4       2537.45       16        1.83  
5       1803.60        8        1.37  
6        400.00        4        2.10  
7       2139.97       16        2.04  
8       1158.70        8        1.34  
9       1495.00       16        1.30  
10       770.00        8        1.60

In [8]:
dataset['CPT']=dataset['Company']+dataset['Product']+dataset['TypeName']
dataset.drop(['Company','Product','TypeName'],axis=1,inplace=True)

In [9]:
dataset.head(10)

Inches                    ScreenResolution                         Cpu  \
1     13.3  IPS Panel Retina Display 2560x1600        Intel Core i5 2.3GHz   
2     13.3                            1440x900        Intel Core i5 1.8GHz   
3     15.6                   Full HD 1920x1080  Intel Core i5 7200U 2.5GHz   
4     15.4  IPS Panel Retina Display 2880x1800        Intel Core i7 2.7GHz   
5     13.3  IPS Panel Retina Display 2560x1600        Intel Core i5 3.1GHz   
6     15.6                            1366x768     AMD A9-Series 9420 3GHz   
7     15.4  IPS Panel Retina Display 2880x1800        Intel Core i7 2.2GHz   
8     13.3                            1440x900        Intel Core i5 1.8GHz   
9     14.0                   Full HD 1920x1080  Intel Core i7 8550U 1.8GHz   
10    14.0         IPS Panel Full HD 1920x1080  Intel Core i5 8250U 1.6GHz   

                 Memory                           Gpu       OpSys  \
1             128GB SSD  Intel Iris Plus Graphics 640       macOS   
2   128GB Flash Storage        Intel HD Graphics 6000       macOS   
3             256GB SSD         Intel HD Graphics 620       No OS   
4             512GB SSD            AMD Radeon Pro 455       macOS   
5             256GB SSD  Intel Iris Plus Graphics 650       macOS   
6             500GB HDD                 AMD Radeon R5  Windows 10   
7   256GB Flash Storage       Intel Iris Pro Graphics    Mac OS X   
8   256GB Flash Storage        Intel HD Graphics 6000       macOS   
9             512GB SSD          Nvidia GeForce MX150  Windows 10   
10            256GB SSD        Intel UHD Graphics 620  Windows 10   

    Price_euros  Ram(GB)  Weight(kg)                           CPT  
1       1339.69        8        1.37     AppleMacBook ProUltrabook  
2        898.94        8        1.34     AppleMacbook AirUltrabook  
3        575.00        8        1.86              HP250 G6Notebook  
4       2537.45       16        1.83     AppleMacBook ProUltrabook  
5       1803.60        8        1.37     AppleMacBook ProUltrabook  
6        400.00        4        2.10          AcerAspire 3Notebook  
7       2139.97       16        2.04     AppleMacBook ProUltrabook  
8       1158.70        8        1.34     AppleMacbook AirUltrabook  
9       1495.00       16        1.30  AsusZenBook UX430UNUltrabook  
10       770.00        8        1.60          AcerSwift 3Ultrabook

In [10]:
categorical_features=[feature for feature in dataset.columns if dataset[feature].dtype=='O']

In [11]:
categorical_features

['ScreenResolution', 'Cpu', 'Memory', 'Gpu', 'OpSys', 'CPT']

In [12]:
for feature in categorical_features:
    labels_ordered=dataset.groupby([feature])['Price_euros'].mean().sort_values().index
    labels_ordered={k:i for i,k in enumerate(labels_ordered,0)}
    dataset[feature]=dataset[feature].map(labels_ordered)

In [13]:
dataset.head(10)

Inches  ScreenResolution  Cpu  Memory  Gpu  OpSys  Price_euros  Ram(GB)  \
1     13.3                26   85      13   80      8      1339.69        8   
2     13.3                13   64      14   45      8       898.94        8   
3     15.6                15   58      20   54      2       575.00        8   
4     15.4                36  111      30   95      8      2537.45       16   
5     13.3                26   99      20   84      8      1803.60        8   
6     15.6                 6   32       9   12      4       400.00        4   
7     15.4                36  106      23   89      5      2139.97       16   
8     13.3                13   64      23   45      8      1158.70        8   
9     14.0                15   72      30   42      4      1495.00       16   
10    14.0                18   59      20   59      4       770.00        8   

    Weight(kg)  CPT  
1         1.37  597  
2         1.34  346  
3         1.86  107  
4         1.83  597  
5         1.37  597  
6         2.10   86  
7         2.04  597  
8         1.34  346  
9         1.30  495  
10        1.60  285

## Feature scaling

In [14]:
scaling_feature=[feature for feature in dataset.columns]
len(scaling_feature)

10

In [15]:
dataset.head()

Inches  ScreenResolution  Cpu  Memory  Gpu  OpSys  Price_euros  Ram(GB)  \
1    13.3                26   85      13   80      8      1339.69        8   
2    13.3                13   64      14   45      8       898.94        8   
3    15.6                15   58      20   54      2       575.00        8   
4    15.4                36  111      30   95      8      2537.45       16   
5    13.3                26   99      20   84      8      1803.60        8   

   Weight(kg)  CPT  
1        1.37  597  
2        1.34  346  
3        1.86  107  
4        1.83  597  
5        1.37  597

In [16]:
feature_scale=[feature for feature in dataset.columns]
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(dataset[feature_scale])

MinMaxScaler()

In [17]:
scaler.transform(dataset[feature_scale])

array([[0.38554217, 0.66666667, 0.72649573, ..., 0.09677419, 0.16957606,
        0.903177  ],
       [0.38554217, 0.33333333, 0.54700855, ..., 0.09677419, 0.16209476,
        0.52344932],
       [0.6626506 , 0.38461538, 0.4957265 , ..., 0.09677419, 0.29177057,
        0.16187595],
       ...,
       [0.46987952, 0.15384615, 0.13675214, ..., 0.        , 0.20199501,
        0.01815431],
       [0.6626506 , 0.15384615, 0.65811966, ..., 0.06451613, 0.37406484,
        0.37518911],
       [0.6626506 , 0.15384615, 0.13675214, ..., 0.03225806, 0.3765586 ,
        0.10438729]])

In [18]:
dataset.head()

Inches  ScreenResolution  Cpu  Memory  Gpu  OpSys  Price_euros  Ram(GB)  \
1    13.3                26   85      13   80      8      1339.69        8   
2    13.3                13   64      14   45      8       898.94        8   
3    15.6                15   58      20   54      2       575.00        8   
4    15.4                36  111      30   95      8      2537.45       16   
5    13.3                26   99      20   84      8      1803.60        8   

   Weight(kg)  CPT  
1        1.37  597  
2        1.34  346  
3        1.86  107  
4        1.83  597  
5        1.37  597

In [19]:
# transform the train and test set
data =pd.DataFrame(scaler.transform(dataset[feature_scale]), columns=feature_scale)

In [20]:
scaler.fit(np.array(dataset['Price_euros']).reshape(-1,1))

MinMaxScaler()

In [21]:
data.head()

Inches  ScreenResolution       Cpu    Memory       Gpu  OpSys  \
0  0.385542          0.666667  0.726496  0.342105  0.733945   1.00   
1  0.385542          0.333333  0.547009  0.368421  0.412844   1.00   
2  0.662651          0.384615  0.495726  0.526316  0.495413   0.25   
3  0.638554          0.923077  0.948718  0.789474  0.871560   1.00   
4  0.385542          0.666667  0.846154  0.526316  0.770642   1.00   

   Price_euros   Ram(GB)  Weight(kg)       CPT  
0     0.196741  0.096774    0.169576  0.903177  
1     0.122353  0.096774    0.162095  0.523449  
2     0.067679  0.096774    0.291771  0.161876  
3     0.398895  0.225806    0.284289  0.903177  
4     0.275038  0.096774    0.169576  0.903177

In [23]:
data.to_csv('laptops_preprocessed_v5.csv',index=False)

# MODEL SELECTION AND PREDICTIONS

In [24]:
dataset=pd.read_csv('laptops_preprocessed_v5.csv')

In [25]:
dataset.head()

Inches  ScreenResolution       Cpu    Memory       Gpu  OpSys  \
0  0.385542          0.666667  0.726496  0.342105  0.733945   1.00   
1  0.385542          0.333333  0.547009  0.368421  0.412844   1.00   
2  0.662651          0.384615  0.495726  0.526316  0.495413   0.25   
3  0.638554          0.923077  0.948718  0.789474  0.871560   1.00   
4  0.385542          0.666667  0.846154  0.526316  0.770642   1.00   

   Price_euros   Ram(GB)  Weight(kg)       CPT  
0     0.196741  0.096774    0.169576  0.903177  
1     0.122353  0.096774    0.162095  0.523449  
2     0.067679  0.096774    0.291771  0.161876  
3     0.398895  0.225806    0.284289  0.903177  
4     0.275038  0.096774    0.169576  0.903177

In [26]:
y=dataset[['Price_euros']]
y.head()

Price_euros
0     0.196741
1     0.122353
2     0.067679
3     0.398895
4     0.275038

In [27]:
X=dataset.drop('Price_euros',axis=1)
X.head()

Inches  ScreenResolution       Cpu    Memory       Gpu  OpSys   Ram(GB)  \
0  0.385542          0.666667  0.726496  0.342105  0.733945   1.00  0.096774   
1  0.385542          0.333333  0.547009  0.368421  0.412844   1.00  0.096774   
2  0.662651          0.384615  0.495726  0.526316  0.495413   0.25  0.096774   
3  0.638554          0.923077  0.948718  0.789474  0.871560   1.00  0.225806   
4  0.385542          0.666667  0.846154  0.526316  0.770642   1.00  0.096774   

   Weight(kg)       CPT  
0    0.169576  0.903177  
1    0.162095  0.523449  
2    0.291771  0.161876  
3    0.284289  0.903177  
4    0.169576  0.903177

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_valid,y_train,y_valid=train_test_split(X,y,train_size=0.75,random_state=0)

In [29]:
selected_feat=[]
for feature in dataset.columns:
    if feature not in 'Price_euros':
        selected_feat.append(feature)

In [30]:
selected_feat

['Inches',
 'ScreenResolution',
 'Cpu',
 'Memory',
 'Gpu',
 'OpSys',
 'Ram(GB)',
 'Weight(kg)',
 'CPT']

In [31]:
X_train.head()

Inches  ScreenResolution       Cpu    Memory       Gpu  OpSys  \
853   0.469880          0.461538  0.803419  0.526316  0.642202    0.5   
916   0.385542          0.384615  0.495726  0.526316  0.495413    0.5   
1034  0.662651          0.384615  0.658120  0.526316  0.431193    0.5   
912   0.662651          0.384615  0.675214  0.526316  0.366972    0.5   
252   0.662651          0.153846  0.273504  0.315789  0.165138    0.5   

       Ram(GB)  Weight(kg)       CPT  
853   0.096774    0.316708  0.878971  
916   0.096774    0.199501  0.494705  
1034  0.096774    0.286783  0.733737  
912   0.064516    0.376559  0.369138  
252   0.032258    0.246883  0.167927

In [32]:
X_given=[[0.46988,0.461538,0.675214,0.921053,0.495413,0.375,0.096774,0.201995,0.161876]]

In [33]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error

model=DecisionTreeRegressor(random_state=0).fit(X_train,y_train)
preds=model.predict(X_valid)
print("MAE:")
print(mean_absolute_error(y_valid,preds))
print("Score:",model.score(X_train,y_train))

MAE:
0.024675638735730376
Score: 0.9996502020588136


In [34]:
print("Score:",model.score(X_valid,y_valid))

Score: 0.880635764176739


In [35]:
print(model.predict(X_given))


[0.06767932]


In [36]:
scaler.inverse_transform(np.array(model.predict(X_given)).reshape(1,-1))

array([[575.]])

In [37]:
dataset.head()

Inches  ScreenResolution       Cpu    Memory       Gpu  OpSys  \
0  0.385542          0.666667  0.726496  0.342105  0.733945   1.00   
1  0.385542          0.333333  0.547009  0.368421  0.412844   1.00   
2  0.662651          0.384615  0.495726  0.526316  0.495413   0.25   
3  0.638554          0.923077  0.948718  0.789474  0.871560   1.00   
4  0.385542          0.666667  0.846154  0.526316  0.770642   1.00   

   Price_euros   Ram(GB)  Weight(kg)       CPT  
0     0.196741  0.096774    0.169576  0.903177  
1     0.122353  0.096774    0.162095  0.523449  
2     0.067679  0.096774    0.291771  0.161876  
3     0.398895  0.225806    0.284289  0.903177  
4     0.275038  0.096774    0.169576  0.903177

In [38]:
from sklearn.linear_model import LinearRegression
model=LinearRegression().fit(X_train,y_train)
preds=model.predict(X_valid)
print("MAE:")
print(mean_absolute_error(y_valid,preds))
print("Score:",model.score(X_train,y_train))

MAE:
0.031567036770185006
Score: 0.8805293924768198


In [39]:
print("Score:",model.score(X_valid,y_valid))

Score: 0.8255407524647055


In [40]:
scaler.inverse_transform(np.array(model.predict(X_given)).reshape(1,-1))

array([[516.91068553]])

In [41]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(n_estimators=250,random_state=0)
model.fit(X_train,y_train)
preds=model.predict(X_valid)
print("MAE:")
print(mean_absolute_error(y_valid,preds))
print("Score:",model.score(X_train,y_train))

<ipython-input-41-a2f03e58a55f>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train,y_train)


MAE:
0.016960807262856974
Score: 0.989756977005614


In [42]:
print("Score:",model.score(X_valid,y_valid))

Score: 0.9375008080731635


In [43]:
scaler.inverse_transform(np.array(model.predict(X_given)).reshape(1,-1))

array([[569.73588]])

In [44]:
from sklearn.linear_model import Ridge
model=Ridge(normalize=False,alpha=0.05)
model.fit(X_train,y_train)
preds=model.predict(X_valid)
print("MAE:")
print(mean_absolute_error(y_valid,preds))
print("Score:",model.score(X_train,y_train))

MAE:
0.0315516817989838
Score: 0.8805202750555038


In [45]:
print("Score:",model.score(X_valid,y_valid))

Score: 0.8254475259750294


In [46]:
scaler.inverse_transform(np.array(model.predict(X_given)).reshape(1,-1))

array([[521.81650102]])

In [47]:
import xgboost as xg
model=xg.XGBRegressor(objective='reg:squarederror',n_estimators=10000)
model.fit(X_train,y_train)
preds=model.predict(X_valid)
print("MAE:")
print(mean_absolute_error(y_valid,preds))
print("Score:",model.score(X_train,y_train))

MAE:
0.018176212202887933
Score: 0.9990099040313901


In [48]:
print("Score:",model.score(X_valid,y_valid))

Score: 0.9333554523538621


In [49]:
val=scaler.inverse_transform(np.array(model.predict(np.array(X_given)).reshape(1,-1)))

In [50]:
from keras.models import Sequential
from keras.layers import Dense
model= Sequential()
model.add(Dense(128, input_dim=9, activation='relu',kernel_initializer='normal'))
model.add(Dense(256, activation='relu',kernel_initializer='normal'))
model.add(Dense(256,activation='relu',kernel_initializer='normal'))
model.add(Dense(256,activation='relu',kernel_initializer='normal'))
model.add(Dense(256,activation='linear',kernel_initializer='normal'))
#model.add(Dense(128,activation='relu',kernel_initializer='normal'))
model.add(Dense(1, activation='linear',kernel_initializer='normal'))
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['accuracy'])

In [51]:
model.fit(X_train, y_train, epochs=100,batch_size=20,validation_data=(X_valid,y_valid))

Epoch 1/100
49/49 [==============================] - 24s 28ms/step - loss: 0.0585 - accuracy: 0.0014 - val_loss: 0.0264 - val_accuracy: 0.0000e+00
Epoch 2/100
49/49 [==============================] - 0s 5ms/step - loss: 0.0217 - accuracy: 6.4532e-04 - val_loss: 0.0232 - val_accuracy: 0.0000e+00
Epoch 3/100
49/49 [==============================] - 0s 5ms/step - loss: 0.0207 - accuracy: 6.3805e-04 - val_loss: 0.0541 - val_accuracy: 0.0000e+00
Epoch 4/100
49/49 [==============================] - 0s 5ms/step - loss: 0.0293 - accuracy: 9.0200e-04 - val_loss: 0.0315 - val_accuracy: 0.0000e+00
Epoch 5/100
49/49 [==============================] - 0s 5ms/step - loss: 0.0197 - accuracy: 0.0022 - val_loss: 0.0240 - val_accuracy: 0.0000e+00
Epoch 6/100
49/49 [==============================] - 0s 5ms/step - loss: 0.0205 - accuracy: 2.9815e-04 - val_loss: 0.0243 - val_accuracy: 0.0000e+00
Epoch 7/100
49/49 [==============================] - 0s 5ms/step - loss: 0.0227 - accuracy: 8.5079e-04 - val_los

49/49 [==============================] - 0s 5ms/step - loss: 0.0193 - accuracy: 0.0014 - val_loss: 0.0216 - val_accuracy: 0.0000e+00
Epoch 57/100
49/49 [==============================] - 0s 5ms/step - loss: 0.0198 - accuracy: 7.2378e-04 - val_loss: 0.0208 - val_accuracy: 0.0000e+00
Epoch 58/100
49/49 [==============================] - 0s 5ms/step - loss: 0.0161 - accuracy: 0.0032 - val_loss: 0.0228 - val_accuracy: 0.0000e+00
Epoch 59/100
49/49 [==============================] - 0s 5ms/step - loss: 0.0178 - accuracy: 8.0509e-04 - val_loss: 0.0250 - val_accuracy: 0.0000e+00
Epoch 60/100
49/49 [==============================] - 0s 5ms/step - loss: 0.0185 - accuracy: 0.0015 - val_loss: 0.0217 - val_accuracy: 0.0000e+00
Epoch 61/100
49/49 [==============================] - 0s 5ms/step - loss: 0.0179 - accuracy: 6.9133e-04 - val_loss: 0.0206 - val_accuracy: 0.0000e+00
Epoch 62/100
49/49 [==============================] - 0s 5ms/step - loss: 0.0201 - accuracy: 0.0027 - val_loss: 0.0230 - val_

In [52]:
results = model.evaluate(X_train, y_train, batch_size=32)
print("test loss, test acc:", results)

31/31 [==============================] - 0s 2ms/step - loss: 0.0156 - accuracy: 0.0020
test loss, test acc: [0.015619811601936817, 0.0020470828749239445]


In [53]:
_, accuracy = model.evaluate(X_train, y_train,verbose=0)
print('Accuracy percentage: %.2f' % (accuracy*100))

Accuracy percentage: 0.20


In [54]:
preds=model.predict(X_valid)
print(mean_absolute_error(y_valid,preds))

0.021576053226108623


In [55]:
scaler.inverse_transform(np.array(model.predict(X_given)).reshape(1,-1))

array([[627.7443]], dtype=float32)

We get best accuracy of 93.33 % on the validation set in the XGBoost model. Hence, we conclude that our model predicts the value predicted by the XGBoost model:

In [56]:
print("Value predicted(in euros):",val[0][0])

Value predicted(in euros): 748.7568
